name: pokedex deploymentPrefix

on:
  push:
    branches:
      - "main"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hellon
        run: |
          echo "Hello jljulioa from pokedex"
      - name: Fecha
        run: |
          date
      - name: hellon
        run: |
          ls -lrta
