name: pokedex deploymentPrefix

on:
  push:
    branches:
      - "main"

jobs:
  hello:
    runs-on: ubuntu-18.04
    steps:
      - name: hellon
        run: |
          echo "Hello jljulioa from pokedex"
